### ISSUE TITLE
I just wanted to say "thank you" for this. :-)

### ISSUE THREAD

**Issue by dertuxmalwieder** [zolagonano/cienli#1]
For my [yaydl project](https://code.rosaelefanten.org/yaydl) ([GitHub mirror](https://github.com/dertuxmalwieder/yaydl)), I needed a ROT-47 implementation because a supported video platform currently uses this. Not being a fan of implementing ciphers myself (because those are a *Solved Problem*), I have seen that CiEnLi seems to be the only existing library which supports ROT-47.

I used it for yaydl 0.5.0 and it seems to work rather well. As the Open Source scene is known for not saying "thank you" a lot, I thought it could be a good idea to break this rule.

Also, welcome to Rust! ;-)

**Comment by zolagonano** [comment]
Thanks.
I'm so glad that this library has been useful to you.
